name: script
description: A sample command-line application.
version: 0.0.1
homepage: https://github.com/v7lin
author: v7lin <v7lin@qq.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  path: ^1.4.1
  args: ^1.5.1
  mime: ^0.9.6+3

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
