name: router_annotation
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/v7lin
author: v7lin <v7lin@qq.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  meta: ^1.1.6

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
