name: router_annotation
description: Router Annotation.
version: 0.1.1
# author: v7lin <v7lin@qq.com>
homepage: https://github.com/v7lin/router_kit

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  meta: ^1.1.6

dev_dependencies:
  test:

  pedantic:
