# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
#  routerCompiler:
#    import: "package:router_compiler/builder.dart"
#    builder_factories: ['routerCompiler']
#    build_extensions: { '.dart': ['.g.dart'] }
#    auto_apply: root_package
#    build_to: source

  pageCompiler:
    import: "package:router_compiler/builder.dart"
    builder_factories: ["pageCompiler"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: root_package
    runs_before: ['router_compiler|routerCompiler']
    build_to: source
