name: router_compiler
description: Flutter Router Compiler.
version: 0.2.0
# author: v7lin <v7lin@qq.com>
homepage: https://github.com/rxreader/router_kit

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  router_annotation: ^0.2.0
#    path: ../router_annotation

  analyzer:
  logging:
  build:
  source_gen:

dev_dependencies:
  test:

  pedantic:

  json_serializable:
