name: router_compiler
description: Flutter Router Compiler.
version: 1.0.0
# author: v7lin <v7lin@qq.com>
homepage: https://github.com/rxreader/router_kit
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  router_annotation:
    path: ../router_annotation

  analyzer: ^1.5.0
  logging: ^1.0.1
  build: ^2.0.1
  source_gen: ^1.0.0

dev_dependencies:
  test:

  pedantic:

  json_serializable:
