name: router_compiler
description: Flutter Router Compiler.
version: 1.0.0
# author: v7lin <v7lin@qq.com>
homepage: https://github.com/HollySite/router_kit
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  router_annotation:
    git:
      url: https://github.com/HollySite/router_kit
      ref: 3ef7d184956617146f0d4ee02e4bbcfa4bc6dfa5
      path: router_annotation

  analyzer: ^1.5.0
  logging: ^1.0.1
  build: ^2.0.1
  source_gen: ^1.0.0

dev_dependencies:
  test:

  pedantic:

  json_serializable:
