name: router_compiler
description: Flutter Router Compiler.
version: 0.1.5
# author: v7lin <v7lin@qq.com>
homepage: https://github.com/v7lin/router_kit

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  router_annotation: ^0.1.0

  analyzer: ^0.39.0
  logging: ^0.11.3+1
  build: '>=0.12.6 <2.0.0'
  source_gen: ^0.9.6

dev_dependencies:
  pedantic:
  test:

  build_runner: ^1.0.0
  build_web_compilers: '>=1.0.0 <3.0.0'
  collection: ^1.14.0

dependency_overrides:
  router_annotation:
    path: ../router_annotation
